# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
